version: "3.8"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: root
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      VIRTUAL_HOST: mongoexpress.localhost
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "HolyShit1"
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      VIRTUAL_HOST: pgadmin.localhost
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
  adminer:
    image: adminer
    environment:
      VIRTUAL_HOST: adminer.localhost
  clickhouse:
    image: "yandex/clickhouse-server:21.12"
    environment:
      - CLICKHOUSE_DB=uptrace
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
  uptrace:
    image: "uptrace/uptrace:latest"
    volumes:
      - ./uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - "14317:14317" # OTLP
      - "14318:14318" # UI and HTTP API
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      VIRTUAL_HOST: uptrace.localhost
      VIRTUAL_PORT: 14318
  zookeeper:
    image: zookeeper
  kafka:
    image: "bitnami/kafka:latest"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      VIRTUAL_HOST: kafdrop.localhost
      VIRTUAL_PORT: 9000
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka
